name: deafconnect
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  avatar_glow: ^3.0.1
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_3d_controller: ^1.3.0
  flutter_chat_bubble: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.9
  flutter_tts: ^3.8.5
  http: ^1.2.1
  intl: ^0.19.0
  path: ^1.9.0
  popover: ^0.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.0
  sqflite: ^2.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo/logo.png"
  remove_alpha_ios: true  

flutter:

  uses-material-design: true
  assets:
  - assets/
  - assets/logo/
  - assets/backgrounds/
  - assets/gifs/
  - assets/avatars/
  - assets/letters/
  - assets/icons/navbar/
  - assets/icons/chat/
  - assets/icons/transcript/
  - assets/icons/settings/
  - assets/icons/settings/
 